
question_data = [
    {"text": "The sky is blue.", "answer": "True"},
    {"text": "The capital of France is Berlin.", "answer": "False"},
    {"text": "2 + 2 equals 4.", "answer": "True"},
    {"text": "The Earth is flat.", "answer": "False"},
    {"text": "Python is a type of snake.", "answer": "True"},
    {"text": "The sun revolves around the Earth.", "answer": "False"},
    {"text": "Water boils at 100 degrees Celsius.", "answer": "True"},
    {"text": "Humans can breathe underwater without assistance.", "answer": "False"},
    {"text": "The Great Wall of China is visible from space.", "answer": "False"},
    {"text": "Light travels faster than sound.", "answer": "True"},
    {"text": "Mount Everest is the tallest mountain on Earth.", "answer": "True"},
    {"text": "Bats are blind.", "answer": "False"},
    {"text": "The human body has four lungs.", "answer": "False"},
    {"text": "Sharks are mammals.", "answer": "False"},
    {"text": "The chemical symbol for gold is Au.", "answer": "True"},
    {"text": "Venus is the closest planet to the Sun.", "answer": "False"},
    {"text": "The Pacific Ocean is the largest ocean on Earth.", "answer": "True"},
    {"text": "Lightning never strikes the same place twice.", "answer": "False"},
    {"text": "Humans share 50% of their DNA with bananas.", "answer": "True"},
    {"text": "The Eiffel Tower is located in Rome.", "answer": "False"},
    {"text": "Sound travels faster in air than in water.", "answer": "False"},
    {"text": "The human heart has four chambers.", "answer": "True"},
    {"text": "Albert Einstein developed the theory of relativity.", "answer": "True"},
    {"text": "The Mona Lisa was painted by Vincent van Gogh.", "answer": "False"},
    {"text": "The largest desert on Earth is the Sahara.", "answer": "True"},
]